### ISSUE TITLE
DECLARATION OF WAR @rythompson

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#25]
It is hereby decreed that @rythompson has underhandedly acquired what is mine and therefore has invoked the wrath of the Archmage. @ArchmageInc has declared war against @rythompson as of 11:21 on Friday March 11th 2016. The Call To Arms shall end at 11:21 on Monday March 14th 2016.

**Comment by ArchmageInc** [comment]
All those who shall join in an alliance with either the Attacker or Defender shall do so during the Call To Arms in public declaration here.

**Comment by jimmyhmiller** [comment]
Should this be closed?

**Comment by ArchmageInc** [comment]
no

**Comment by ArchmageInc** [comment]
There is no rule which states that any active wars were to be closed. Unless the rules otherwise direct this motion it shall stand, regardless of if anything happens to it right now.

**Comment by rythompson** [comment]
There are no more rules for war, so therefore I declare victory because I can.

**Comment by ArchmageInc** [comment]
In time, I will bring sexy back.

**Comment by jimmyhmiller** [comment]
War has officially ended!

**Comment by ArchmageInc** [comment]
for now
