### ISSUE TITLE
CALL TO JUDGEMENT

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#54]
This is a call to judgement concerning the addition of active player @allensb in PR #51 in which he was granted a value of 30 points.

I find this to be a violation of

> **320.** No point values may be manipulated outside of the rules.

As there is no rule which indicates the starting value for new players, the creation of points would be a manipulation outside of the rules and therefore a violation.

**Comment by ArchmageInc** [comment]
> **212.** If players disagree about the legality of a move or the interpretation or application of a rule, then the player preceding the one moving is to be the Judge and decide the question. Disagreement for the purposes of this rule may be created by the insistence of any player. This process is called invoking Judgment.
> 
> The Judge's Judgment may be overruled only by a unanimous vote of the other players taken before the next turn is begun. If a Judge's Judgment is overruled, then the player preceding the Judge in the playing order becomes the new Judge for the question, and so on, except that no player is to be Judge during his or her own turn or during the turn of a team-mate.
> 
> Unless a Judge is overruled, one Judge settles all questions arising from the game until the next turn is begun, including questions as to his or her own legitimacy and jurisdiction as Judge.
> 
> New Judges are not bound by the decisions of old Judges. New Judges may, however, settle only those questions on which the players currently disagree and that affect the completion of the turn in which Judgment was invoked. All decisions by Judges shall be in accordance with all the rules then in effect; but when the rules are silent, inconsistent, or unclear on the point at issue, then the Judge shall consider game-custom and the spirit of the game before applying other standards.

---

> **305.** No player may be a judge in a dispute in which they are involved.

---

> **308.** If any players disagree about the legality of a move or the interpretation or application of a rule, any player may call for a Judgement. A Judgement is created by opening an issue. The issue must contain a summary of the dispute at hand.

So... who is the one moving right now?

**Comment by jimmyhmiller** [comment]
I plan on submitting a rule soon to choose who is judge that will hopefully help with this problem. I might try to take the time and fix all judging things.

**Comment by ArchmageInc** [comment]
This will now be closed and the call to judgement abandoned.
