### ISSUE TITLE
Nomic Bot Error

### ISSUE THREAD

**Issue by ArchmageInc** [nomicness/a-whole-new-world#99]
> TypeError: methodName is not a function
>     at /nomic-bot/dist/command-processors/buy-processor.js:65:24
>     at _fulfilled (/nomic-bot/node_modules/q/q.js:834:54)
>     at self.promiseDispatch.done (/nomic-bot/node_modules/q/q.js:863:30)
>     at Promise.promise.promiseDispatch (/nomic-bot/node_modules/q/q.js:796:13)
>     at /nomic-bot/node_modules/q/q.js:604:44
>     at runSingle (/nomic-bot/node_modules/q/q.js:137:13)
>     at flush (/nomic-bot/node_modules/q/q.js:125:13)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ArchmageInc** [comment]
This occurred when attempting /buy 1 farm

**Comment by jimmyhmiller** [comment]
Will investigate tonight.

**Comment by ArchmageInc** [comment]
This has been resolved by #100
